# Generated by Django 5.1.4 on 2025-10-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='event',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='overtime_edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
