# Generated by Django 5.1.4 on 2025-10-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancerecord_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='overtime_edit_count',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='admin_adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='event',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
