# Generated by Django 5.1.4 on 2025-11-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_balanceadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='overtime_edited',
            field=models.BooleanField(default=False),
        ),
    ]
