# Generated by Django 5.1.4 on 2025-11-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendancerecord_overtime_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='original_overtime_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
