# Generated by Django 5.1.4 on 2025-11-15 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_event_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='event_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.event'),
        ),
    ]
