# Generated by Django 5.1.4 on 2026-01-08 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_populate_balanceadjustment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balanceadjustment',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='balanceadjustment',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='balanceadjustment',
            name='profile',
        ),
        migrations.AddField(
            model_name='event',
            name='client_venue',
            field=models.CharField(blank=True, help_text='Client venue/location', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='equipments_delivered',
            field=models.TextField(blank=True, help_text='List of equipments delivered to this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='setup_date',
            field=models.DateField(blank=True, help_text='Date when setup starts', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='setup_end_date',
            field=models.DateField(blank=True, help_text='Date when setup is complete / Event ends', null=True),
        ),
        migrations.AlterField(
            model_name='balanceadjustment',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='balanceadjustment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
