# Generated by Django 5.1.4 on 2026-01-08 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_expensereimbursement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_crew',
            field=models.ManyToManyField(blank=True, help_text='Select users assigned for event day work', related_name='event_day_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='setup_crew',
            field=models.ManyToManyField(blank=True, help_text='Select users assigned to setup/teardown work', related_name='setup_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
