# Generated by Django 5.1.4 on 2026-01-08 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_event_event_crew_event_setup_crew'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='supper_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Supper allowance for salaried employees', max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_type',
            field=models.CharField(choices=[('casual', 'Casual Laborer'), ('salaried', 'Salaried Employee')], default='casual', help_text='Is this person a casual laborer or salaried employee?', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_role',
            field=models.CharField(blank=True, choices=[('repair', 'Repair Technician'), ('driver', 'Driver'), ('accountant', 'Accountant'), ('planner', 'Event Planner'), ('cleaner', 'Cleaner'), ('other', 'Other')], help_text='Job role (for salaried employees)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Monthly salary amount (for salaried employees)', max_digits=10),
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(help_text='First day of the month for which salary is paid')),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Base monthly salary', max_digits=10)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0.0, help_text='Total overtime pay for the month', max_digits=10)),
                ('supper_allowance', models.DecimalField(decimal_places=2, default=0.0, help_text='Total supper allowance for the month', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount paid (base + overtime + supper)', max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_salary_payments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month_year'],
                'unique_together': {('user', 'month_year')},
            },
        ),
    ]
