# Generated by Django 5.1.4 on 2026-01-08 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_attendancerecord_supper_allowance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('job_role', models.CharField(choices=[('repair_technician', 'Repair Technician'), ('driver', 'Driver'), ('accountant', 'Accountant'), ('event_planner', 'Event Planner'), ('cleaner', 'Cleaner'), ('other', 'Other')], max_length=50)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('bank_account', models.CharField(blank=True, help_text='Bank account for salary payments', max_length=50)),
                ('id_photo', models.FileField(blank=True, upload_to='onboarding/id_photos/')),
                ('employment_letter', models.FileField(blank=True, upload_to='onboarding/letters/')),
                ('bank_details', models.FileField(blank=True, upload_to='onboarding/bank_details/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='If rejected, provide reason for rejection')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
