# Generated by Django 5.1.4 on 2026-01-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_employeeonboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeonboarding',
            name='job_role',
            field=models.CharField(blank=True, choices=[('repair_technician', 'Repair Technician'), ('driver', 'Driver'), ('accountant', 'Accountant'), ('event_planner', 'Event Planner'), ('cleaner', 'Cleaner'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeonboarding',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
