# Generated by Django 5.1.4 on 2026-01-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_alter_employeeonboarding_job_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeonboarding',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
