# Generated by Django 5.1.4 on 2026-01-23 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_alter_employeeonboarding_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('attendance', 'Attendance Recorded'), ('attendance_edit', 'Attendance Edited'), ('admin_adjustment', 'Admin Adjustment'), ('reimbursement', 'Reimbursement Approved'), ('salary_payment', 'Salary Payment'), ('payment_marked', 'Payment Marked'), ('payment_received', 'Payment Received')], max_length=50)),
                ('amount_change', models.DecimalField(decimal_places=2, help_text='Change in balance (can be negative)', max_digits=10)),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of related object (attendance, reimbursement, etc.)', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object', max_length=50)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('other', 'Other')], default='bank_transfer', max_length=50)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction/reference number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
