# Generated by Django 5.1.4 on 2026-01-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_balancechange_paymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereimbursement',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
