# Generated by Django 5.1.4 on 2026-01-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_expensereimbursement_is_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalanceChange',
        ),
    ]
