# Generated by Django 5.1.4 on 2026-01-26 07:54

import attendance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_delete_balancechange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_in_time',
            field=models.TimeField(default=attendance.models.get_current_time),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=attendance.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='expensereimbursement',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(help_text='Email address of recipient', max_length=254)),
                ('notification_type', models.CharField(choices=[('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('crew_assignment', 'Crew Assignment'), ('payment_approved', 'Payment Approved'), ('reimbursement_approved', 'Reimbursement Approved'), ('salary_processed', 'Salary Processed'), ('attendance_recorded', 'Attendance Recorded'), ('event_reminder', 'Event Reminder'), ('crew_confirmation', 'Crew Confirmation Request')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_sent', 'created_at'], name='attendance__is_sent_3f4254_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Role in this event (e.g., Sound Engineer, Technician, Setup)', max_length=100)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('completed', 'Completed')], default='invited', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes for crew member')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='attendance.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_crew_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Event Crew',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='attendance__event_i_f40115_idx'), models.Index(fields=['user', 'status'], name='attendance__user_id_f77af9_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number in format 254xxxxxxxxx', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in KSH', max_digits=10)),
                ('payment_purpose', models.CharField(help_text='Purpose of payment (salary, reimbursement, etc.)', max_length=255)),
                ('checkout_request_id', models.CharField(help_text='M-Pesa checkout request ID', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('merchant_request_id', models.CharField(blank=True, max_length=255)),
                ('result_code', models.IntegerField(blank=True, help_text='M-Pesa result code', null=True)),
                ('result_description', models.TextField(blank=True)),
                ('receipt_number', models.CharField(blank=True, help_text='M-Pesa receipt number', max_length=100)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'M-Pesa Payments',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='attendance__user_id_45b758_idx'), models.Index(fields=['checkout_request_id'], name='attendance__checkou_ee4b28_idx')],
            },
        ),
    ]
