# Generated by Django 5.1.4 on 2026-01-26 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_alter_attendancerecord_amount_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Equipment name (e.g., Microphone, Speaker, Mixer)', max_length=255)),
                ('equipment_type', models.CharField(help_text='Type of equipment (e.g., Microphone, Speaker, Amplifier, Cable, Stand)', max_length=100)),
                ('serial_number', models.CharField(help_text='Unique serial number or ID', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description and specs')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('needs_repair', 'Needs Repair')], default='good', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('location', models.CharField(blank=True, help_text='Current storage location', max_length=255)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['equipment_type', 'name'],
                'indexes': [models.Index(fields=['status'], name='attendance__status_8f225b_idx'), models.Index(fields=['equipment_type', 'status'], name='attendance__equipme_fc15fa_idx'), models.Index(fields=['serial_number'], name='attendance__serial__09c11d_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('planning', 'Planning Phase'), ('setup_scheduled', 'Setup Scheduled'), ('setup_in_progress', 'Setup In Progress'), ('setup_complete', 'Setup Complete'), ('event_in_progress', 'Event In Progress'), ('event_complete', 'Event Complete'), ('teardown_in_progress', 'Teardown In Progress'), ('teardown_complete', 'Teardown Complete'), ('closed', 'Event Closed')], default='planning', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Current status description for clients')),
                ('client_email', models.EmailField(blank=True, help_text='Client email for progress updates', max_length=254)),
                ('last_update_sent', models.DateTimeField(blank=True, null=True)),
                ('update_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily')], default='daily', max_length=20)),
                ('setup_started_at', models.DateTimeField(blank=True, null=True)),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('event_started_at', models.DateTimeField(blank=True, null=True)),
                ('event_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='attendance.event')),
            ],
            options={
                'verbose_name_plural': 'Event Progress',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive Maintenance'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('calibration', 'Calibration'), ('cleaning', 'Cleaning')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(help_text='What maintenance was performed')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('parts_replaced', models.TextField(blank=True, help_text='List of parts replaced')),
                ('notes', models.TextField(blank=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='attendance.equipment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['equipment', 'status'], name='attendance__equipme_050155_idx'), models.Index(fields=['scheduled_date', 'status'], name='attendance__schedul_0edde0_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_use', 'In Use'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('missing', 'Missing')], default='assigned', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('condition_before', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('needs_repair', 'Needs Repair')], default='good', max_length=20)),
                ('condition_after', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('needs_repair', 'Needs Repair')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about equipment during event')),
                ('damage_report', models.TextField(blank=True, help_text='Detailed damage report if applicable')),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assignments_given', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_assignments', to='attendance.equipment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assignments', to='attendance.event')),
            ],
            options={
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['event', 'status'], name='attendance__event_i_cd6ff0_idx'), models.Index(fields=['equipment', 'status'], name='attendance__equipme_602ef5_idx')],
                'unique_together': {('event', 'equipment')},
            },
        ),
    ]
