# Generated by Django 5.1.4 on 2026-01-28 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_event_event_crew_event_setup_crew_eventcrew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventCrew',
        ),
    ]
