# Generated by Django 5.1.4 on 2026-01-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_delete_eventcrew'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereimbursement',
            name='checkout_request_id',
            field=models.CharField(blank=True, help_text='M-Pesa checkout request ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensereimbursement',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When the reimbursement was paid', null=True),
        ),
    ]
